name: "Workspace test"

on:
  workflow_dispatch:

env:
  HYPHIZED_WORKFLOW_NAME: ${{ env.GITHUB_WORKFLOW | tr -C '[:alnum:]._' '-' | sed -e 's/--*/-/g' -e 's/^-*//g' -e 's/-*$//g' }}

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Prints workspace"
        run: |
          echo ${{ github.workflow }}

      - name: "Prints workflow name #2"
        run: |
          echo ${{ env.GITHUB_WORKFLOW }}

      - name: "Prints workflow name hyphenized #1"
        run: |
          echo ${{ github.workflow }} | tr -C '[:alnum:]._' '-' | sed -e 's/--*/-/g' -e 's/^-*//g' -e 's/-*$//g'

      - name: "Prints workflow name hyphenized #2"
        run: echo ${{ env.HYPHENIZED_WORKFLOW_NAME }}

      - name: "Show environment variables"
        run: env
