name: "The workflow for setting the environment variable"

on:
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Prints environment variables
        run: env

      - name: Exports environment variable
        id: set-output
        run: echo "::set-output name=FOOBAR::Blablubb"

      - name: Print output variable
        run: echo "${{ steps.set-output.outputs.FOOBAR }}"

      - name: Prints environment variables
        run: env
