name: "Tests comments in command"

on:
  pull_request: ~
  workflow_dispatch:
    inputs:
      overwrite_env:
        description: 'Overwrite Environment Variables'
        required: false

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment variables - 1st step
        run: |
          env

      - name: Set variable through normal bash
        run: |
          echo "That's a test text that generates test data." | grep \
            # this comment shouldn't produce any issues
            -o \
            'te[a-zA-Z]*'
