name: "Env variable resolution"

on:
  workflow_dispatch:

env:
  FOO_TAG: 'foo'

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Initialize env variables"
        shell: bash
        run: |
          echo "BAR2_TAG=${{ env.FOO_TAG }}bar" >> $GITHUB_ENV
      - name: "Print env variables"
        shell: bash
        run: |
          echo "$BAR2_TAG"
          echo "$FOO_TAG"
