name: "The for setting the variable"

on:
  pull_request: ~
  workflow_dispatch:
    inputs:
      overwrite_env:
        description: 'Overwrite Environment Variables'
        required: false

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    env:
      E_VARIABLE_JOB_LEVEL: ${{ github.head_ref || "foobar" }}
    steps:
      - name: Show environment variables - 1st step
        run: |
          env

      - name: Set variable through normal bash
        if: ${{ always() }}
        run: echo "Setting the varable within the steps"
        env:
          E_VARIABLE_STEP_LEVEL: "value #2"

      - name: Show environment variables - 2nd step
        run: |
          env
