name: "The workflow for setting the environment variable"

on:
  workflow_dispatch:
    flinkVersion:
        description: 'The Flink version the VVP Flink version is based on (e.g. 1.13.3 for 1.13.3-stream1 or 1.14.0 for 1.14.0-stream2)'
        required: true

env:
  FOOBAR_TAG: '${{ github.event.inputs.flinkVersion }}-foobar'

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout #1
        uses: actions/checkout@v2
        with:
          path: $FOOBAR_TAG

      - name: Checkout #2
        uses: actions/checkout@v2
        with:
          path: ${{ env.FOOBAR_TAG }}
