name: "The for setting the variable"

on:
  pull_request: ~
  workflow_dispatch:
    inputs:
      overwrite_env:
        description: 'Overwrite Environment Variables'
        required: false

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    env:
      E_VARIABLE_JOB_LEVEL: ${{ github.head_ref }}
    steps:
      - name: Show environment variables - 1st step
        run: |
          env

      - name: Set variable through normal bash
        run: |
          echo "E_VARIABLE_STEP_LEVEL=${GITHUB_HEAD_REF:-$GITHUB_WORKFLOW}" >> $GITHUB_ENV

      - name: Show environment variables - 2nd step
        run: |
          env

      - name: Print selective environment variables
        run: |
          cat << EOF
          E2E Test Run Parameters
          =======================

          Commit SHA: ${{ github.sha }}
          Registry: ${{ steps.tags.outputs.registry }}/branches
          Docker tag: $BRANCH
          Test suite: ${{ matrix.test }}
          Overwritten Environment Variables: ${{ github.event.inputs.overwrite_env }}
          EOF
