name: "Workspace test"

on:
  workflow_dispatch:

jobs:
  stringify:
    name: "Stringify"
    runs-on: ubuntu-latest
    outputs:
      stringified-workflow-name: ${{ steps.workflow-prep-step.stringified-workflow-name }}
    steps:
      - name: "Stringify workflow name"
        id: workflow-prep-step
        run: |
          stringified_workflow_name=$(echo "${{ github.workflow }}" | tr -C '[:alnum:]._' '-' |  tr '[:upper:]' '[:lower:]' | sed -e 's/--*/-/g' -e 's/^-*//g' -e 's/-*$//g')
          echo ${stringified_workflow_name}
          echo "::set-output name=stringified-workflow-name::${stringified_workflow_name}"
      - name: "Stringify workflow name"
        run: echo ${{ steps.workflow-prep-step.outputs.stringified-workflow-name }}

  test:
    name: "Use stringified version"
    needs: stringify
    runs-on: ubuntu-20.04
    steps:
      - name: "Upload build artifacts"
        run: echo "logs-test-${{ needs.stringify.outputs.stringified-workflow-name }}-${{ github.run_number }}"