name: "Test for accessing the matrix parameter"

on:
  pull_request: ~
  workflow_dispatch:
    inputs:
      flinkVersion:
        description: 'Flink Version'
      streamVersion:
        description: 'Stream Version'
env:
  STREAM_VERSION: ${{ github.event.inputs.flinkVersion }}-stream${{ github.event.inputs.streamVersion }}
  SPRING_VERSION: ${{ github.event.inputs.flinkVersion }}-spring${{ github.event.inputs.streamVersion }}

jobs:
  test-workflow:
    name: 'Test workflow for ${{ env.STREAM_VERSION }} and ${{ env.SPRING_VERSION }}'
    runs-on: ubuntu-latest
    steps:
      - name: 'Step 1 of ${{ env.STREAM_VERSION }} and ${{ env.SPRING_VERSION }}'
        run: |
          echo "Stream version: $STREAM_VERSION"
          echo "Spring version: $SPRING_VERSION"
