name: "The workflow for setting the environment variable"

on:
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Prints environment variables
        run: env

      - name: Exports environment variable
        id: set-output
        run: echo "::set-output name=FOOBAR::Blablubb"

      - name: Print output variable
        env:
          MIGRATED_FOOBAR: ${{ steps.set-output.outputs.FOOBAR }}
        run: env

      - name: Prints environment variables
        run: env
