name: "Tests env sharing between steps"

on:
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v3
      - name: "Source utils"
        shell: bash
        run: |
          source ./.github/scripts/test-utils.sh
          
          foo
          echo $FOOBAR_VAR
      - name: "Check whether utils are still accessible"
        shell: bash
        run: |
          foo
          echo $FOOBAR_VAR