name: "Env variable resolution"

on:
  workflow_dispatch:

env:
  FOO_TAG: 'foo'

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    env:
      BAR2_TAG: "${{ FOO_TAG }}bar"
      BAR3_TAG: "${FOO_TAG}bar"
    steps:
      - name: "Print env variables"
        shell: bash
        run: |
          echo "$BAR2_TAG"
          echo "$BAR3_TAG"
          echo "$FOO_TAG"
