name: "Test Composite Actions"

on:
  workflow_dispatch:

env:
  CHECKOUT_DIR: checkout

jobs:
  test:
    name: "Test Composite Actions Job"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/${{ env.CHECKOUT_DIR }}

      - name: "Runs Composite Action"
        uses: ./${{ env.CHECKOUT_DIR }}/.github/actions/test-action
        id: composite-step
        with:
          who-to-greet: Matthias

      - name: "Prints output"
        run: echo ${{ steps.composite-step.outputs.random-number }}