name: "Workspace test"

on:
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Show environment variables - 1st step
        run: |
          env

      - name: Prints workspace variable
        run: echo ${{ github.workspace }}

      - name: Show environment variables - 2nd step
        run: |
          env
